package pgscan

import "testing"

func TestAlterTableColumnExtended(t *testing.T) {
	tests := []struct {
		sql     string
		desc    string
		subtype AlterTableType
	}{
		{"ALTER TABLE t ALTER COLUMN c SET STATISTICS 100", "set statistics", AT_SetStatistics},
		{"ALTER TABLE t ALTER COLUMN c SET STORAGE PLAIN", "set storage", AT_SetStorage},
		{"ALTER TABLE t ALTER COLUMN c SET COMPRESSION lz4", "set compression", AT_SetCompression},
		{"ALTER TABLE t ALTER COLUMN c ADD GENERATED ALWAYS AS IDENTITY", "add identity always", AT_AddIdentity},
		{"ALTER TABLE t ALTER COLUMN c ADD GENERATED BY DEFAULT AS IDENTITY", "add identity by default", AT_AddIdentity},
		{"ALTER TABLE t ALTER COLUMN c DROP IDENTITY", "drop identity", AT_DropIdentity},
		{"ALTER TABLE t ALTER COLUMN c DROP IDENTITY IF EXISTS", "drop identity if exists", AT_DropIdentity},
		{"ALTER TABLE t ALTER COLUMN c SET EXPRESSION AS (a + b)", "set expression", AT_SetExpression},
		{"ALTER TABLE t ALTER COLUMN c DROP EXPRESSION", "drop expression", AT_DropExpression},
		{"ALTER TABLE t ALTER COLUMN c DROP EXPRESSION IF EXISTS", "drop expression if exists", AT_DropExpression},
	}
	for _, tt := range tests {
		t.Run(tt.desc, func(t *testing.T) {
			stmt := parseOne(t, tt.sql)
			at := stmt.(*AlterTableStmt)
			if len(at.Cmds) != 1 {
				t.Fatalf("expected 1 cmd, got %d", len(at.Cmds))
			}
			if at.Cmds[0].Subtype != tt.subtype {
				t.Fatalf("expected subtype %d, got %d", tt.subtype, at.Cmds[0].Subtype)
			}
		})
	}
}

func TestAlterTableConstraintOps(t *testing.T) {
	tests := []struct {
		sql     string
		desc    string
		subtype AlterTableType
	}{
		{"ALTER TABLE t ALTER CONSTRAINT mycon", "alter constraint", AT_AlterConstraint},
		{"ALTER TABLE t VALIDATE CONSTRAINT mycon", "validate constraint", AT_ValidateConstraint},
	}
	for _, tt := range tests {
		t.Run(tt.desc, func(t *testing.T) {
			stmt := parseOne(t, tt.sql)
			at := stmt.(*AlterTableStmt)
			if at.Cmds[0].Subtype != tt.subtype {
				t.Fatalf("expected subtype %d, got %d", tt.subtype, at.Cmds[0].Subtype)
			}
		})
	}
}

func TestAlterTableCluster(t *testing.T) {
	stmt := parseOne(t, "ALTER TABLE t CLUSTER ON myidx")
	at := stmt.(*AlterTableStmt)
	if at.Cmds[0].Subtype != AT_ClusterOn {
		t.Fatalf("expected AT_ClusterOn, got %d", at.Cmds[0].Subtype)
	}
	if at.Cmds[0].Name != "myidx" {
		t.Fatalf("expected 'myidx', got %q", at.Cmds[0].Name)
	}
}

func TestAlterTableSetWithout(t *testing.T) {
	tests := []struct {
		sql     string
		desc    string
		subtype AlterTableType
	}{
		{"ALTER TABLE t SET WITHOUT CLUSTER", "without cluster", AT_DropCluster},
		{"ALTER TABLE t SET LOGGED", "set logged", AT_SetLogged},
		{"ALTER TABLE t SET UNLOGGED", "set unlogged", AT_SetUnLogged},
		{"ALTER TABLE t SET TABLESPACE myts", "set tablespace", AT_SetTableSpace},
		{"ALTER TABLE t SET ACCESS METHOD heap", "set access method", AT_SetAccessMethod},
	}
	for _, tt := range tests {
		t.Run(tt.desc, func(t *testing.T) {
			stmt := parseOne(t, tt.sql)
			at := stmt.(*AlterTableStmt)
			if at.Cmds[0].Subtype != tt.subtype {
				t.Fatalf("expected subtype %d, got %d", tt.subtype, at.Cmds[0].Subtype)
			}
		})
	}
}

func TestAlterTableEnableDisableTrigger(t *testing.T) {
	tests := []struct {
		sql     string
		desc    string
		subtype AlterTableType
	}{
		{"ALTER TABLE t ENABLE TRIGGER mytrig", "enable trigger", AT_EnableTrig},
		{"ALTER TABLE t DISABLE TRIGGER mytrig", "disable trigger", AT_DisableTrig},
		{"ALTER TABLE t ENABLE TRIGGER ALL", "enable trigger all", AT_EnableTrigAll},
		{"ALTER TABLE t DISABLE TRIGGER ALL", "disable trigger all", AT_DisableTrigAll},
		{"ALTER TABLE t ENABLE TRIGGER USER", "enable trigger user", AT_EnableTrigUser},
		{"ALTER TABLE t DISABLE TRIGGER USER", "disable trigger user", AT_DisableTrigUser},
		{"ALTER TABLE t ENABLE ALWAYS TRIGGER mytrig", "enable always trigger", AT_EnableAlwaysTrig},
		{"ALTER TABLE t ENABLE REPLICA TRIGGER mytrig", "enable replica trigger", AT_EnableReplicaTrig},
	}
	for _, tt := range tests {
		t.Run(tt.desc, func(t *testing.T) {
			stmt := parseOne(t, tt.sql)
			at := stmt.(*AlterTableStmt)
			if at.Cmds[0].Subtype != tt.subtype {
				t.Fatalf("expected subtype %d, got %d", tt.subtype, at.Cmds[0].Subtype)
			}
		})
	}
}

func TestAlterTableEnableDisableRule(t *testing.T) {
	tests := []struct {
		sql     string
		desc    string
		subtype AlterTableType
	}{
		{"ALTER TABLE t ENABLE RULE myrule", "enable rule", AT_EnableRule},
		{"ALTER TABLE t DISABLE RULE myrule", "disable rule", AT_DisableRule},
		{"ALTER TABLE t ENABLE ALWAYS RULE myrule", "enable always rule", AT_EnableAlwaysRule},
		{"ALTER TABLE t ENABLE REPLICA RULE myrule", "enable replica rule", AT_EnableReplicaRule},
	}
	for _, tt := range tests {
		t.Run(tt.desc, func(t *testing.T) {
			stmt := parseOne(t, tt.sql)
			at := stmt.(*AlterTableStmt)
			if at.Cmds[0].Subtype != tt.subtype {
				t.Fatalf("expected subtype %d, got %d", tt.subtype, at.Cmds[0].Subtype)
			}
		})
	}
}

func TestAlterTableInherit(t *testing.T) {
	tests := []struct {
		sql     string
		desc    string
		subtype AlterTableType
	}{
		{"ALTER TABLE t INHERIT parent", "inherit", AT_AddInherit},
		{"ALTER TABLE t NO INHERIT parent", "no inherit", AT_DropInherit},
	}
	for _, tt := range tests {
		t.Run(tt.desc, func(t *testing.T) {
			stmt := parseOne(t, tt.sql)
			at := stmt.(*AlterTableStmt)
			if at.Cmds[0].Subtype != tt.subtype {
				t.Fatalf("expected subtype %d, got %d", tt.subtype, at.Cmds[0].Subtype)
			}
		})
	}
}

func TestAlterTableOfNotOf(t *testing.T) {
	tests := []struct {
		sql     string
		desc    string
		subtype AlterTableType
	}{
		{"ALTER TABLE t OF mytype", "of", AT_AddOf},
		{"ALTER TABLE t NOT OF", "not of", AT_DropOf},
	}
	for _, tt := range tests {
		t.Run(tt.desc, func(t *testing.T) {
			stmt := parseOne(t, tt.sql)
			at := stmt.(*AlterTableStmt)
			if at.Cmds[0].Subtype != tt.subtype {
				t.Fatalf("expected subtype %d, got %d", tt.subtype, at.Cmds[0].Subtype)
			}
		})
	}
}

func TestAlterTableOwner(t *testing.T) {
	stmt := parseOne(t, "ALTER TABLE t OWNER TO alice")
	at := stmt.(*AlterTableStmt)
	if at.Cmds[0].Subtype != AT_ChangeOwner {
		t.Fatalf("expected AT_ChangeOwner, got %d", at.Cmds[0].Subtype)
	}
	if at.Cmds[0].Name != "alice" {
		t.Fatalf("expected 'alice', got %q", at.Cmds[0].Name)
	}
}

func TestAlterTableReplicaIdentity(t *testing.T) {
	tests := []struct {
		sql  string
		desc string
		name string
	}{
		{"ALTER TABLE t REPLICA IDENTITY DEFAULT", "default", "default"},
		{"ALTER TABLE t REPLICA IDENTITY FULL", "full", "full"},
		{"ALTER TABLE t REPLICA IDENTITY NOTHING", "nothing", "nothing"},
		{"ALTER TABLE t REPLICA IDENTITY USING INDEX myidx", "using index", "myidx"},
	}
	for _, tt := range tests {
		t.Run(tt.desc, func(t *testing.T) {
			stmt := parseOne(t, tt.sql)
			at := stmt.(*AlterTableStmt)
			if at.Cmds[0].Subtype != AT_ReplicaIdentity {
				t.Fatalf("expected AT_ReplicaIdentity, got %d", at.Cmds[0].Subtype)
			}
			if at.Cmds[0].Name != tt.name {
				t.Fatalf("expected name %q, got %q", tt.name, at.Cmds[0].Name)
			}
		})
	}
}

func TestAlterTableRowLevelSecurity(t *testing.T) {
	tests := []struct {
		sql     string
		desc    string
		subtype AlterTableType
	}{
		{"ALTER TABLE t ENABLE ROW LEVEL SECURITY", "enable rls", AT_EnableRowSecurity},
		{"ALTER TABLE t DISABLE ROW LEVEL SECURITY", "disable rls", AT_DisableRowSecurity},
		{"ALTER TABLE t FORCE ROW LEVEL SECURITY", "force rls", AT_ForceRowSecurity},
		{"ALTER TABLE t NO FORCE ROW LEVEL SECURITY", "no force rls", AT_NoForceRowSecurity},
	}
	for _, tt := range tests {
		t.Run(tt.desc, func(t *testing.T) {
			stmt := parseOne(t, tt.sql)
			at := stmt.(*AlterTableStmt)
			if at.Cmds[0].Subtype != tt.subtype {
				t.Fatalf("expected subtype %d, got %d", tt.subtype, at.Cmds[0].Subtype)
			}
		})
	}
}
