package tests

import (
	"testing"

	"github.com/jespino/gopgsql/parser"
)

func TestAlterTableColumnExtended(t *testing.T) {
	tests := []struct {
		sql     string
		desc    string
		subtype parser.AlterTableType
	}{
		{"ALTER TABLE t ALTER COLUMN c SET STATISTICS 100", "set statistics", parser.AT_SetStatistics},
		{"ALTER TABLE t ALTER COLUMN c SET STORAGE PLAIN", "set storage", parser.AT_SetStorage},
		{"ALTER TABLE t ALTER COLUMN c SET COMPRESSION lz4", "set compression", parser.AT_SetCompression},
		{"ALTER TABLE t ALTER COLUMN c ADD GENERATED ALWAYS AS IDENTITY", "add identity always", parser.AT_AddIdentity},
		{"ALTER TABLE t ALTER COLUMN c ADD GENERATED BY DEFAULT AS IDENTITY", "add identity by default", parser.AT_AddIdentity},
		{"ALTER TABLE t ALTER COLUMN c DROP IDENTITY", "drop identity", parser.AT_DropIdentity},
		{"ALTER TABLE t ALTER COLUMN c DROP IDENTITY IF EXISTS", "drop identity if exists", parser.AT_DropIdentity},
		{"ALTER TABLE t ALTER COLUMN c SET EXPRESSION AS (a + b)", "set expression", parser.AT_SetExpression},
		{"ALTER TABLE t ALTER COLUMN c DROP EXPRESSION", "drop expression", parser.AT_DropExpression},
		{"ALTER TABLE t ALTER COLUMN c DROP EXPRESSION IF EXISTS", "drop expression if exists", parser.AT_DropExpression},
	}
	for _, tt := range tests {
		t.Run(tt.desc, func(t *testing.T) {
			stmt := parseOne(t, tt.sql)
			at := stmt.(*parser.AlterTableStmt)
			if len(at.Cmds) != 1 {
				t.Fatalf("expected 1 cmd, got %d", len(at.Cmds))
			}
			if at.Cmds[0].Subtype != tt.subtype {
				t.Fatalf("expected subtype %d, got %d", tt.subtype, at.Cmds[0].Subtype)
			}
		})
	}
}


func TestAlterTableConstraintOps(t *testing.T) {
	tests := []struct {
		sql     string
		desc    string
		subtype parser.AlterTableType
	}{
		{"ALTER TABLE t ALTER CONSTRAINT mycon", "alter constraint", parser.AT_AlterConstraint},
		{"ALTER TABLE t VALIDATE CONSTRAINT mycon", "validate constraint", parser.AT_ValidateConstraint},
	}
	for _, tt := range tests {
		t.Run(tt.desc, func(t *testing.T) {
			stmt := parseOne(t, tt.sql)
			at := stmt.(*parser.AlterTableStmt)
			if at.Cmds[0].Subtype != tt.subtype {
				t.Fatalf("expected subtype %d, got %d", tt.subtype, at.Cmds[0].Subtype)
			}
		})
	}
}


func TestAlterTableCluster(t *testing.T) {
	stmt := parseOne(t, "ALTER TABLE t CLUSTER ON myidx")
	at := stmt.(*parser.AlterTableStmt)
	if at.Cmds[0].Subtype != parser.AT_ClusterOn {
		t.Fatalf("expected parser.AT_ClusterOn, got %d", at.Cmds[0].Subtype)
	}
	if at.Cmds[0].Name != "myidx" {
		t.Fatalf("expected 'myidx', got %q", at.Cmds[0].Name)
	}
}


func TestAlterTableSetWithout(t *testing.T) {
	tests := []struct {
		sql     string
		desc    string
		subtype parser.AlterTableType
	}{
		{"ALTER TABLE t SET WITHOUT CLUSTER", "without cluster", parser.AT_DropCluster},
		{"ALTER TABLE t SET LOGGED", "set logged", parser.AT_SetLogged},
		{"ALTER TABLE t SET UNLOGGED", "set unlogged", parser.AT_SetUnLogged},
		{"ALTER TABLE t SET TABLESPACE myts", "set tablespace", parser.AT_SetTableSpace},
		{"ALTER TABLE t SET ACCESS METHOD heap", "set access method", parser.AT_SetAccessMethod},
	}
	for _, tt := range tests {
		t.Run(tt.desc, func(t *testing.T) {
			stmt := parseOne(t, tt.sql)
			at := stmt.(*parser.AlterTableStmt)
			if at.Cmds[0].Subtype != tt.subtype {
				t.Fatalf("expected subtype %d, got %d", tt.subtype, at.Cmds[0].Subtype)
			}
		})
	}
}


func TestAlterTableEnableDisableTrigger(t *testing.T) {
	tests := []struct {
		sql     string
		desc    string
		subtype parser.AlterTableType
	}{
		{"ALTER TABLE t ENABLE TRIGGER mytrig", "enable trigger", parser.AT_EnableTrig},
		{"ALTER TABLE t DISABLE TRIGGER mytrig", "disable trigger", parser.AT_DisableTrig},
		{"ALTER TABLE t ENABLE TRIGGER ALL", "enable trigger all", parser.AT_EnableTrigAll},
		{"ALTER TABLE t DISABLE TRIGGER ALL", "disable trigger all", parser.AT_DisableTrigAll},
		{"ALTER TABLE t ENABLE TRIGGER USER", "enable trigger user", parser.AT_EnableTrigUser},
		{"ALTER TABLE t DISABLE TRIGGER USER", "disable trigger user", parser.AT_DisableTrigUser},
		{"ALTER TABLE t ENABLE ALWAYS TRIGGER mytrig", "enable always trigger", parser.AT_EnableAlwaysTrig},
		{"ALTER TABLE t ENABLE REPLICA TRIGGER mytrig", "enable replica trigger", parser.AT_EnableReplicaTrig},
	}
	for _, tt := range tests {
		t.Run(tt.desc, func(t *testing.T) {
			stmt := parseOne(t, tt.sql)
			at := stmt.(*parser.AlterTableStmt)
			if at.Cmds[0].Subtype != tt.subtype {
				t.Fatalf("expected subtype %d, got %d", tt.subtype, at.Cmds[0].Subtype)
			}
		})
	}
}


func TestAlterTableEnableDisableRule(t *testing.T) {
	tests := []struct {
		sql     string
		desc    string
		subtype parser.AlterTableType
	}{
		{"ALTER TABLE t ENABLE RULE myrule", "enable rule", parser.AT_EnableRule},
		{"ALTER TABLE t DISABLE RULE myrule", "disable rule", parser.AT_DisableRule},
		{"ALTER TABLE t ENABLE ALWAYS RULE myrule", "enable always rule", parser.AT_EnableAlwaysRule},
		{"ALTER TABLE t ENABLE REPLICA RULE myrule", "enable replica rule", parser.AT_EnableReplicaRule},
	}
	for _, tt := range tests {
		t.Run(tt.desc, func(t *testing.T) {
			stmt := parseOne(t, tt.sql)
			at := stmt.(*parser.AlterTableStmt)
			if at.Cmds[0].Subtype != tt.subtype {
				t.Fatalf("expected subtype %d, got %d", tt.subtype, at.Cmds[0].Subtype)
			}
		})
	}
}


func TestAlterTableInherit(t *testing.T) {
	tests := []struct {
		sql     string
		desc    string
		subtype parser.AlterTableType
	}{
		{"ALTER TABLE t INHERIT parent", "inherit", parser.AT_AddInherit},
		{"ALTER TABLE t NO INHERIT parent", "no inherit", parser.AT_DropInherit},
	}
	for _, tt := range tests {
		t.Run(tt.desc, func(t *testing.T) {
			stmt := parseOne(t, tt.sql)
			at := stmt.(*parser.AlterTableStmt)
			if at.Cmds[0].Subtype != tt.subtype {
				t.Fatalf("expected subtype %d, got %d", tt.subtype, at.Cmds[0].Subtype)
			}
		})
	}
}


func TestAlterTableOfNotOf(t *testing.T) {
	tests := []struct {
		sql     string
		desc    string
		subtype parser.AlterTableType
	}{
		{"ALTER TABLE t OF mytype", "of", parser.AT_AddOf},
		{"ALTER TABLE t NOT OF", "not of", parser.AT_DropOf},
	}
	for _, tt := range tests {
		t.Run(tt.desc, func(t *testing.T) {
			stmt := parseOne(t, tt.sql)
			at := stmt.(*parser.AlterTableStmt)
			if at.Cmds[0].Subtype != tt.subtype {
				t.Fatalf("expected subtype %d, got %d", tt.subtype, at.Cmds[0].Subtype)
			}
		})
	}
}


func TestAlterTableOwner(t *testing.T) {
	stmt := parseOne(t, "ALTER TABLE t OWNER TO alice")
	at := stmt.(*parser.AlterTableStmt)
	if at.Cmds[0].Subtype != parser.AT_ChangeOwner {
		t.Fatalf("expected parser.AT_ChangeOwner, got %d", at.Cmds[0].Subtype)
	}
	if at.Cmds[0].Name != "alice" {
		t.Fatalf("expected 'alice', got %q", at.Cmds[0].Name)
	}
}


func TestAlterTableReplicaIdentity(t *testing.T) {
	tests := []struct {
		sql  string
		desc string
		name string
	}{
		{"ALTER TABLE t REPLICA IDENTITY DEFAULT", "default", "default"},
		{"ALTER TABLE t REPLICA IDENTITY FULL", "full", "full"},
		{"ALTER TABLE t REPLICA IDENTITY NOTHING", "nothing", "nothing"},
		{"ALTER TABLE t REPLICA IDENTITY USING INDEX myidx", "using index", "myidx"},
	}
	for _, tt := range tests {
		t.Run(tt.desc, func(t *testing.T) {
			stmt := parseOne(t, tt.sql)
			at := stmt.(*parser.AlterTableStmt)
			if at.Cmds[0].Subtype != parser.AT_ReplicaIdentity {
				t.Fatalf("expected parser.AT_ReplicaIdentity, got %d", at.Cmds[0].Subtype)
			}
			if at.Cmds[0].Name != tt.name {
				t.Fatalf("expected name %q, got %q", tt.name, at.Cmds[0].Name)
			}
		})
	}
}


func TestAlterTableRowLevelSecurity(t *testing.T) {
	tests := []struct {
		sql     string
		desc    string
		subtype parser.AlterTableType
	}{
		{"ALTER TABLE t ENABLE ROW LEVEL SECURITY", "enable rls", parser.AT_EnableRowSecurity},
		{"ALTER TABLE t DISABLE ROW LEVEL SECURITY", "disable rls", parser.AT_DisableRowSecurity},
		{"ALTER TABLE t FORCE ROW LEVEL SECURITY", "force rls", parser.AT_ForceRowSecurity},
		{"ALTER TABLE t NO FORCE ROW LEVEL SECURITY", "no force rls", parser.AT_NoForceRowSecurity},
	}
	for _, tt := range tests {
		t.Run(tt.desc, func(t *testing.T) {
			stmt := parseOne(t, tt.sql)
			at := stmt.(*parser.AlterTableStmt)
			if at.Cmds[0].Subtype != tt.subtype {
				t.Fatalf("expected subtype %d, got %d", tt.subtype, at.Cmds[0].Subtype)
			}
		})
	}
}


func TestAlterTableAddColumn(t *testing.T) {
	s := parseOne(t, "ALTER TABLE t ADD COLUMN name text NOT NULL")
	alt, ok := s.(*parser.AlterTableStmt)
	if !ok {
		t.Fatalf("expected parser.AlterTableStmt, got %T", s)
	}
	if len(alt.Cmds) != 1 {
		t.Fatalf("expected 1 cmd, got %d", len(alt.Cmds))
	}
	cmd := alt.Cmds[0]
	if cmd.Subtype != parser.AT_AddColumn {
		t.Errorf("expected parser.AT_AddColumn, got %d", cmd.Subtype)
	}
	cd := cmd.Def.(*parser.ColumnDef)
	if cd.Colname != "name" {
		t.Errorf("expected name, got %s", cd.Colname)
	}
}


func TestAlterTableDropColumn(t *testing.T) {
	s := parseOne(t, "ALTER TABLE t DROP COLUMN old_col CASCADE")
	alt := s.(*parser.AlterTableStmt)
	cmd := alt.Cmds[0]
	if cmd.Subtype != parser.AT_DropColumn {
		t.Errorf("expected parser.AT_DropColumn, got %d", cmd.Subtype)
	}
	if cmd.Name != "old_col" {
		t.Errorf("expected old_col, got %s", cmd.Name)
	}
	if cmd.Behavior != parser.DROP_CASCADE {
		t.Error("expected CASCADE")
	}
}


func TestAlterTableAlterType(t *testing.T) {
	s := parseOne(t, "ALTER TABLE t ALTER COLUMN col SET DATA TYPE bigint")
	alt := s.(*parser.AlterTableStmt)
	cmd := alt.Cmds[0]
	if cmd.Subtype != parser.AT_AlterColumnType {
		t.Errorf("expected parser.AT_AlterColumnType, got %d", cmd.Subtype)
	}
	tn := cmd.Def.(*parser.TypeName)
	if tn.Names[1] != "int8" {
		t.Errorf("expected int8, got %v", tn.Names)
	}
}


func TestAlterTableSetNotNull(t *testing.T) {
	s := parseOne(t, "ALTER TABLE t ALTER COLUMN col SET NOT NULL")
	alt := s.(*parser.AlterTableStmt)
	if alt.Cmds[0].Subtype != parser.AT_SetNotNull {
		t.Errorf("expected parser.AT_SetNotNull, got %d", alt.Cmds[0].Subtype)
	}
}


func TestAlterTableDropNotNull(t *testing.T) {
	s := parseOne(t, "ALTER TABLE t ALTER COLUMN col DROP NOT NULL")
	alt := s.(*parser.AlterTableStmt)
	if alt.Cmds[0].Subtype != parser.AT_DropNotNull {
		t.Errorf("expected parser.AT_DropNotNull, got %d", alt.Cmds[0].Subtype)
	}
}


func TestAlterTableSetDefault(t *testing.T) {
	s := parseOne(t, "ALTER TABLE t ALTER COLUMN col SET DEFAULT 0")
	alt := s.(*parser.AlterTableStmt)
	if alt.Cmds[0].Subtype != parser.AT_SetDefault {
		t.Errorf("expected parser.AT_SetDefault, got %d", alt.Cmds[0].Subtype)
	}
}


func TestAlterTableDropDefault(t *testing.T) {
	s := parseOne(t, "ALTER TABLE t ALTER COLUMN col DROP DEFAULT")
	alt := s.(*parser.AlterTableStmt)
	if alt.Cmds[0].Subtype != parser.AT_DropDefault {
		t.Errorf("expected parser.AT_DropDefault, got %d", alt.Cmds[0].Subtype)
	}
}


func TestAlterTableAddConstraint(t *testing.T) {
	s := parseOne(t, "ALTER TABLE t ADD CONSTRAINT uq_col UNIQUE (col)")
	alt := s.(*parser.AlterTableStmt)
	cmd := alt.Cmds[0]
	if cmd.Subtype != parser.AT_AddConstraint {
		t.Errorf("expected parser.AT_AddConstraint, got %d", cmd.Subtype)
	}
	c := cmd.Def.(*parser.Constraint)
	if c.Conname != "uq_col" {
		t.Errorf("expected uq_col, got %s", c.Conname)
	}
}


func TestAlterTableDropConstraint(t *testing.T) {
	s := parseOne(t, "ALTER TABLE t DROP CONSTRAINT my_constraint")
	alt := s.(*parser.AlterTableStmt)
	cmd := alt.Cmds[0]
	if cmd.Subtype != parser.AT_DropConstraint {
		t.Errorf("expected parser.AT_DropConstraint, got %d", cmd.Subtype)
	}
	if cmd.Name != "my_constraint" {
		t.Errorf("expected my_constraint, got %s", cmd.Name)
	}
}


func TestAlterTableRenameTo(t *testing.T) {
	s := parseOne(t, "ALTER TABLE old_name RENAME TO new_name")
	alt := s.(*parser.AlterTableStmt)
	cmd := alt.Cmds[0]
	if cmd.Subtype != parser.AT_RenameTable {
		t.Errorf("expected parser.AT_RenameTable, got %d", cmd.Subtype)
	}
	if cmd.Name != "new_name" {
		t.Errorf("expected new_name, got %s", cmd.Name)
	}
}


func TestAlterTableRenameColumn(t *testing.T) {
	s := parseOne(t, "ALTER TABLE t RENAME COLUMN old_col TO new_col")
	alt := s.(*parser.AlterTableStmt)
	cmd := alt.Cmds[0]
	if cmd.Subtype != parser.AT_RenameColumn {
		t.Errorf("expected parser.AT_RenameColumn, got %d", cmd.Subtype)
	}
	if cmd.Name != "old_col" {
		t.Errorf("expected old_col, got %s", cmd.Name)
	}
}


func TestAlterTableIfExists(t *testing.T) {
	s := parseOne(t, "ALTER TABLE IF EXISTS t ADD COLUMN col integer")
	alt := s.(*parser.AlterTableStmt)
	if !alt.MissingOk {
		t.Error("expected MissingOk=true")
	}
}


func TestAlterTableMultipleCmds(t *testing.T) {
	s := parseOne(t, "ALTER TABLE t ADD COLUMN a integer, ADD COLUMN b text")
	alt := s.(*parser.AlterTableStmt)
	if len(alt.Cmds) != 2 {
		t.Fatalf("expected 2 cmds, got %d", len(alt.Cmds))
	}
}

